apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: default
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: http
    port: 80
    targetPort: http
  selector:
    app: nginx
