apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: liveness-http
spec:
  containers:
  - name: liveness
    image: nginx
    livenessProbe:
      httpGet:
        path: /healthz
        port: 80
      initialDelaySeconds: 3
      timeoutSeconds: 3
      periodSeconds: 3
      successThreshold: 1 #Must be 1 for liveness
      failureThreshold: 5

